const nodoface = require('../api/nodoface');
let argv = process.argv.slice(2);
console.log(argv);
let img = nodoface.readImage(argv[0]);
console.log(`Image: rows:${img.height()}, cols:${img.width()}, channels:${img.channels()}`);
nodoface.showImage(img, "Show Image");
nodoface.waitKey(0);
img = nodoface.readImage(argv[0], asGray=true);
nodoface.showImage(img, 'output', true);
nodoface.waitKey(0);
nodoface.destroyAllWindows();
